project:
  type: website

website:
  title: "Principled Statistics in the Age of AI"
  navbar:
    right:
      - text: "Program"
        href: index.qmd
      - text: "Talks"
        href: talks.qmd

format:
  html:
    theme: cosmo
    css: styles.css
