project:
  type: website
  output-dir: docs

website:
  title: "Principled Statistics in the Age of AI"
  navbar:
    right:
      - text: "Program"
        href: index.qmd
      - text: "Talks"
        href: talks.qmd
      - text: "Register"
        href: registration.qmd

  page-navigation: true 

format:
  html:
    theme: yeti
    css: styles.css
    include-after-body:
      - text: <script data-collect-dnt="true" async src="https://scripts.simpleanalyticscdn.com/latest.js"></script> <script async src="https://scripts.simpleanalyticscdn.com/auto-events.js"></script> <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif?collect-dnt=true" alt="" referrerpolicy="no-referrer-when-downgrade"/></noscript>


editor: visual

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true    