---
title: "Principled Statistics in the Age of AI"
title-block: false
---

<div class="site-title-container">
  <h1 class="site-title">Principled Statistics in the Age of AI</h1>
</div>

<div style="text-align: center;">

*Principled Statistics in the Age of AI* is a one-day workshop organized as part of Prof. Xiao-Li Meng's (Harvard University) visit to Chalmers University of Technology as a <a href="https://www.chalmers.se/en/current/news/2026-jubilee-professors-appointed/" target="_blank">2026 Jubilee Professor</a>. The workshop will bring together researchers working across statistics, machine learning, causal inference and privacy to discuss how principled statistical thinking can guide science in the context of AI. Featuring invited talks from leading international and local researchers, the workshop is designed to foster an intimate and discussion-rich atmosphere with ample time for conversation and exchange.

</div>

Lunch and fika will be provided.

**Location:** A Working Lab (on the Chalmers campus), <a href="https://maps.app.goo.gl/Fnc3tzz2wM4yNCALA" target="_blank">Sven Hultins Gata 5, 412 58 Göteborg</a> 

**Date and time:** 9am–4pm, Friday, 5 June 2026


## Program 

::: {.schedule-table}

| Time | Session | Details |
|--------|----------------|------------|
| 09:00–09:30 | Welcome & Opening Remarks | Adel Daoud |
| 09:35–10:20 | Learning Trajectories of Large Neural Networks: A Statistical Analysis | Ashkan Panahi |
| 10:20–10:50 | Morning Fika | Extended break for discussion |
| 10:50–11:35 | Persuasive Privacy | Joshua Bon |
| 11:40–12:25 | Learning causally sound and interpretable composite endpoints for clinical trials | Fredrik Johansson |
| 12:25–13:25 | Lunch | At <a href="https://www.instagram.com/wastegbg/" target="_blank">Waste</a> |
| 13:25–14:10 | Talk (Title TBD) | Cory McCartan |
| 14:10–14:40 | Afternoon Fika | Discussion break |
| 14:40–15:55 | *Keynote Address:* From a Cauchy Surprise to the Half-Cauchy Miracle | Xiao-Li Meng |
| 15:55–16:00 | Closing Remarks | Adel Daoud |

:::

## Talks and Speakers

See the full talk listings and bios on the [Talks page](talks.qmd).


## Registration

Registration is free but mandatory. Please register using the form on the [Registration page](registration.qmd).

Registrations are due by Friday, May 29.


<br><br>

### Organizers
<a href="https://www.adeldaoud.com/" target="_blank">Adel Daoud</a>  & <a href="https://jameshbailie.github.io/" target="_blank">James Bailie</a>

<a href="https://aidevlab.org/" target="_blank">AI & Global Development Lab</a>

**Contact:** [last name] [at] chalmers [dot] se (for both Adel and James).
